[package]
name = "chain-storage"
version = "0.4.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Storage of Crypto.com Chain node (Merkle trie, transaction metadata etc.)"
readme = "README.md"
edition = "2018"

[dependencies]
blake3 = "0.3.0"
kvdb = "0.5"
kvdb-rocksdb = "0.7"
kvdb-memorydb = "0.5"
chain-core = { path = "../chain-core" }
bit-vec = { version = "0.6.1", features = ["serde_no_std"] }
starling = "3.1.4"
parity-scale-codec = { features = ["derive"], version = "1.3" }
integer-encoding = "1.1.5"
anyhow = "1.0"
jellyfish-merkle = { git = "https://github.com/crypto-com/jellyfish-merkle-tree.git", rev = "9d040b0b87e9e619482ac3ca89edc8429f6fa901" }
libra-crypto = { git = "https://github.com/crypto-com/jellyfish-merkle-tree.git", rev = "9d040b0b87e9e619482ac3ca89edc8429f6fa901" }

[dev-dependencies]
quickcheck = "0.9"
