language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
            - kcov       
cache: cargo
rust:
  - stable
  - beta
  - nightly
env:
  - RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
matrix:
  allow_failures:
    - rust: nightly

script:
- cargo clean
- cargo build
- cargo test
- |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    rustfmt --version || rustup component add rustfmt
    cargo fmt -- --check --color=auto
    cargo-clippy --version || rustup component add clippy
    cargo clippy -- -D warnings 
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/deps/chain_abci-* &&
    kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/deps/client_core-* &&
    kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/deps/dev_utils-* &&
    kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/deps/kvdb-* &&
    kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/deps/kvdb_memorydb-* &&
    bash <(curl -s https://codecov.io/bash) &&
    echo "Uploaded code coverage";
  fi