language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
            - kcov       
cache: cargo
rust:
  - stable
  - beta
  - nightly
env:
  - RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
matrix:
  allow_failures:
    - rust: nightly

script:
- cargo clean
- cargo build
- cargo test
- |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    rustfmt --version || rustup component add rustfmt
    cargo fmt -- --check --color=auto
    cargo-clippy --version || rustup component add clippy
    cargo clippy -- -D warnings 
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo-kcov --version || cargo install cargo-kcov;
    cargo kcov --all;
    bash <(curl -s https://codecov.io/bash);
  fi