[workspace]

members = [
    "chain-abci",
    "chain-core",
    "dev-utils",
    "chain-enclave/enclave-app",
    "kvdb",
    "kvdb-memorydb",
    "signer-core",
    "signer-cli",
    "signer-rpc",
]
