[package]
name = "tdb-app-runner"
version = "0.5.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
aesm-client = {version = "0.5", features = ["sgxs"] }
enclave-runner = "0.4"
env_logger = "0.7"
log = "0.4"
sgxs-loaders = "0.2"
structopt = "0.3"
tokio = { version = "0.2", features = ["tcp"] }

enclave-utils = { path = "../../../chain-tx-enclave-next/enclave-utils" }
