[package]
name = "enclave-utils"
version = "0.4.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Platform independent enclave utilities (sealing, attestation primitives...)."
readme = "../../README.md"
edition = "2018"

[dependencies]
aead = { version = "0.2", optional = true }
aes = {version = "0.3", optional = true}
aes-gcm = { version = "0.5", optional = true }
base64 = { version = "0.12", optional = true }
cmac = { version = "0.2", optional = true }
crypto-mac = { version = "0.7", optional = true }
regex = { version = "1.3", optional = true }
ring = { version = "0.16", optional = true }
sgx-isa = { version = "0.3", optional = true }
thiserror = { version = "1.0", optional = true }
webpki = { version = "0.21", optional = true }
x509-parser = {version = "0.6", optional = true }
zeroize = { version = "1.1", optional = true }

[features]
crypto = ["aes", "base64", "cmac", "crypto-mac/std", "regex", "ring", "thiserror", "webpki", "x509-parser"]
sealing = ["aead", "aes-gcm", "sgx-isa", "zeroize"]
sgxstd = ["sgx-isa/sgxstd"]
