version: '3'

services:
  chain0:
    build: .
    volumes:
      - ./disk:/root/disk
      - ./disk/config0:/root/config
      - /nix:/nix
    devices:
      - /dev/sgx
    image: chain_test0
    ports:
       - ${JAIL_CLIENT_RPC:-9981}:9981
       - ${JAIL_CHAIN_RPC:-26657}:26657
    command: /root/disk/go_test.sh
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      APP_HASH:  $APP_HASH
      SPID: $SPID
      IAS_API_KEY: $IAS_API_KEY
      SGX_MODE: HW
      NETWORK_ID: AB
      RUSTFLAGS: -Ctarget-feature=+aes,+ssse3
      APP_PORT: 25933
      TX_ENCLAVE_STORAGE: /enclave-storage

  chain1:
    build: .
    volumes:
      - ./disk:/root/disk
      - ./disk/config1:/root/config
      - /nix:/nix
    devices:
      - /dev/sgx
    image: chain_test1
    command: /root/disk/go_test.sh
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug    
      APP_HASH: $APP_HASH
      SPID: $SPID
      IAS_API_KEY: $IAS_API_KEY
      SGX_MODE: HW
      NETWORK_ID: AB
      RUSTFLAGS: -Ctarget-feature=+aes,+ssse3
      APP_PORT: 25933
      TX_ENCLAVE_STORAGE: /enclave-storage
