[package]
name = "chain-abci"
version = "0.0.1"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Pre-alpha version prototype of Crypto.com Chain node (Tendermint ABCI application)"
readme = "README.md"
edition = "2018"

[dependencies]
abci = "0.5.3"
chain-core = { path = "../chain-core" }
log = "0.4.0"
env_logger = "0.6.1"
bit-vec = "0.6.0"
kvdb = "0.1"
kvdb-rocksdb = "0.1.4"
kvdb-memorydb = "0.1"
starling = { version = "2.5.3", git = "https://github.com/ChosunOne/merkle_bit.git", rev = "679a0bfe7ca104a86073ddcf1bf020909d6fd1f1" }
byteorder = "1.3.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.3"
protobuf = "2.2.0"
integer-encoding = "1.0.5"
clap = { features = ["yaml"], version = "2.33.0" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "4c178ca90965ccf5b1b235e346e836ca65b2a549" }
blake2 = "0.8"
ethbloom = "0.5.0"
parity-codec = { features = ["derive"], version = "3.5.1" }

[dev-dependencies]
quickcheck = "0.8"
criterion = "0.2"
digest = "0.8"
sha3 = "0.8"

[[bench]]
name = "hashes"
harness = false

[[bench]]
name = "tx"
harness = false
