[package]
name = "client-common"
version = "0.4.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
chain-tx-filter = { path = "../chain-tx-filter" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "d50d5998a11064591d86583b297130d6d9636aa5", features = ["serde", "zeroize", "rand", "recovery", "endomorphism", "musig"] }
rand = "0.7"
log = "0.4.8"
aes-gcm-siv = "0.4"
aes = "0.3"
blake3 = "0.3.0"
rust-argon2 = "0.8"
hex = "0.4"
base64 = "0.11"
secstr = { version = "0.4.0", features = ["serde"] }
zeroize = "1.1"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
sled = { version = "0.31.0", optional = true }
serde_json = "1.0"
parity-scale-codec = { features = ["derive"], version = "1.3" }
tungstenite = { version = "0.10", default-features = false, optional = true }
tendermint = { git = "https://github.com/crypto-com/tendermint-rs.git", default-features=false, rev="44a3d5953bcabc7b9e2e8a0f56b2624b796a46f9" }
itertools = "0.9"
indexmap = "1.3"

[dev-dependencies]
quickcheck = "0.9"

[features]
default = ["sled", "websocket-rpc"]
websocket-rpc = ["tungstenite"]
