[package]
name = "client-common"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
chain-tx-filter = { path = "../chain-tx-filter" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "c5ef4fad2d439d58f1d5deab4de0fc88ce0c8b7d", features = ["serde", "zeroize", "rand", "recovery", "endomorphism", "musig"] }
rand = "0.7"
log = "0.4"
miscreant = "0.4"
blake2 = "0.8"
hex = "0.4"
base64 = "0.10"
secstr = { version = "0.3.2", features = ["serde"] }
zeroize = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
sled = { version = "0.28", optional = true }
jsonrpc = { version = "0.11", optional = true }
serde_json = { version = "1.0", optional = true }
parity-scale-codec = { features = ["derive"], version = "1.0" }
websocket = { version = "0.23", default-features = false, features = ["sync"], optional = true }

[features]
default = ["sled", "websocket-rpc"]
http-rpc = ["jsonrpc", "serde_json"]
websocket-rpc = ["websocket", "serde_json"]
