[package]
name = "chain-core"
version = "0.1.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Library with core types and serialization for the use in external tools"
readme = "../README.md"
edition = "2018"

[dependencies]
digest = "0.8"
sha3 = "0.8"
hex = "0.3"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "a67ac07f98e3a9bdd10ff2822ae0340b7962fd2c", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
blake2 = "0.8"
serde_json = "1.0"
parity-codec = { features = ["derive"], version = "3.5.1" }
base64 = "0.10"

[dev-dependencies]
quickcheck = "0.8"