version: "3"

services:
  tendermint:
    image: "tendermint/tendermint:v${TENDERMINT_VERSION:-0.32.8}"
    command: node --proxy_app=chain-abci:26658 --rpc.laddr=tcp://0.0.0.0:26657 --consensus.create_empty_blocks=true
    user: root
    volumes:
      - "./${TENDERMINT_WITHFEE_DIRECTORY}:/tendermint"
    ports:
      - ${TENDERMINT_RPC_PORT:-26657}:26657
  chain-abci:
    image: "${CHAIN_DOCKER_IMAGE:-integration-tests-chain}"
    command: "chain-abci --host=0.0.0.0 --port=26658 --chain_id=${CHAIN_ID} --genesis_app_hash=${WITHFEE_APP_HASH} --enclave_server=tcp://chain-tx-enclave:25933 --tx_query=chain-tx-query-enclave:25944 --data=/.storage"
    volumes:
      - "./${CHAIN_ABCI_WITHFEE_DIRECTORY}:/.storage"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
  chain-tx-enclave:
    image: "${CHAIN_TX_ENCLAVE_DOCKER_IMAGE:-integration-tests-chain}"
    volumes:
      - "./${ENCLAVE_WITHFEE_DIRECTORY}:/.storage"
    devices:
      - "${DOCKER_SGX_DEVICE_BINDING}"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      TX_ENCLAVE_STORAGE: /.storage
      SGX_MODE: ${SGX_MODE}
      NETWORK_ID: ${NETWORK_ID}
      APP_PORT_VALIDATION: 25933
    working_dir: /crypto-chain/bin/validation
    command: "bash ${TX_ENCLAVE_ENTRY_POINT}"
  chain-tx-query-enclave:
    image: "${CHAIN_TX_ENCLAVE_QUERY_DOCKER_IMAGE:-integration-tests-chain}"
    devices:
      - "${DOCKER_SGX_DEVICE_BINDING}"
    environment:
      RUST_BACKTRACE: 1
      SGX_MODE: ${SGX_MODE}
      NETWORK_ID: ${NETWORK_ID}
      SPID: ${SPID}
      IAS_API_KEY: ${IAS_API_KEY}
      RUST_LOG: debug
      TX_QUERY_TIMEOUT: 120
      APP_PORT_QUERY: 25944
      TX_VALIDATION_CONN: tcp://chain-tx-enclave:25933
    working_dir: /crypto-chain/bin/query
    command: "bash ${TX_ENCLAVE_ENTRY_POINT}"
  client-rpc:
    image: "${CHAIN_DOCKER_IMAGE:-integration-tests-chain}"
    command: wait-for-it.sh ${WITH_FEE_CLIENT_RPC_WAIT_URL} --timeout=60 -- client-rpc --host=0.0.0.0 --port=26659 --chain-id=${CHAIN_ID} --storage-dir=/.storage --websocket-url=ws://tendermint:26657/websocket
    volumes:
      - "./${WALLET_STORAGE_WITHFEE_DIRECTORY}:/.storage"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    ports:
      - ${CLIENT_RPC_PORT:-26659}:26659

  tendermint-zerofee:
    image: "tendermint/tendermint:v${TENDERMINT_VERSION:-0.32.0}"
    command: node --proxy_app=chain-abci-zerofee:26658 --rpc.laddr=tcp://0.0.0.0:26657 --consensus.create_empty_blocks=true
    user: root
    volumes:
      - "./${TENDERMINT_ZEROFEE_DIRECTORY}:/tendermint"
    ports:
      - ${TENDERMINT_ZEROFEE_RPC_PORT:-16657}:26657
  chain-abci-zerofee:
    image: "${CHAIN_DOCKER_IMAGE:-integration-tests-chain}"
    command: "chain-abci --host=0.0.0.0 --port=26658 --chain_id=${CHAIN_ID} --genesis_app_hash=${ZEROFEE_APP_HASH} --enclave_server=tcp://chain-tx-enclave-zerofee:25933 --tx_query=chain-tx-query-enclave-zerofee:25944 --data=/.storage"
    volumes:
      - "./${CHAIN_ABCI_ZEROFEE_DIRECTORY}:/.storage"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
  chain-tx-enclave-zerofee:
    image: "${CHAIN_TX_ENCLAVE_DOCKER_IMAGE:-integration-tests-chain-tx-enclave}"
    volumes:
      - "./${ENCLAVE_ZEROFEE_DIRECTORY}:/.storage"
    devices:
      - "${DOCKER_SGX_DEVICE_BINDING}"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      TX_ENCLAVE_STORAGE: /.storage
      SGX_MODE: ${SGX_MODE}
      NETWORK_ID: ${NETWORK_ID}
      APP_PORT_VALIDATION: 25933
    working_dir: /crypto-chain/bin/validation
    entrypoint: "bash ${TX_ENCLAVE_ENTRY_POINT}"
  chain-tx-query-enclave-zerofee:
    image: "${CHAIN_TX_ENCLAVE_QUERY_DOCKER_IMAGE:-integration-tests-chain-tx-query-enclave}"
    devices:
      - "${DOCKER_SGX_DEVICE_BINDING}"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      NETWORK_ID: ${NETWORK_ID}
      TX_QUERY_TIMEOUT: 120
      SPID: ${SPID}
      IAS_API_KEY: ${IAS_API_KEY}
      TX_VALIDATION_CONN: tcp://chain-tx-enclave-zerofee:25933
      SGX_MODE: ${SGX_MODE}
      APP_PORT_QUERY: 25944
    working_dir: /crypto-chain/bin/query
    entrypoint: "bash ${TX_ENCLAVE_ENTRY_POINT}"
  client-rpc-zerofee:
    image: "${CHAIN_DOCKER_IMAGE:-integration-tests-chain}"
    command: wait-for-it.sh ${ZERO_FEE_CLIENT_RPC_WAIT_URL} --timeout=60 --strict -- client-rpc --host=0.0.0.0 --port=26659 --chain-id=${CHAIN_ID} --storage-dir=/.storage --websocket-url=ws://tendermint-zerofee:26657/websocket
    volumes:
      - "./${WALLET_STORAGE_ZEROFEE_DIRECTORY}:/.storage"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    ports:
      - ${CLIENT_RPC_ZEROFEE_PORT:-16659}:26659
