[package]
name = "tdb-enclave-app"
version = "0.5.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]

[target.'cfg(target_env = "sgx")'.dependencies]
env_logger = { version = "0.7", default-features = false }
log = "0.4"
parity-scale-codec = "1.3"
rs-libc = "0.2"
rustls = "0.17"
thread-pool = "0.1"

chain-core = { path = "../../../chain-core", default-features = false, features = ["edp"] }
enclave-protocol = { path = "../../../enclave-protocol", features = ["edp"] }
ra-client = { path = "../../../chain-tx-enclave-next/enclave-ra/ra-client" }
ra-enclave = { path = "../../../chain-tx-enclave-next/enclave-ra/ra-enclave" }

# [patch.crates-io]
# ring = { git = "https://github.com/crypto-com/ring.git", rev = "4e1862fb0df9efaf2d2c1ec8cacb1e53104f3daa" }
